apiVersion: v1
kind: Service
metadata:
  name: easyclaim-frontend-service
  labels:
    name: easyclaim-frontend-service
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32011
  selector:
    name: easyclaim-frontend-pod
  type: NodePort